/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdcc6",
        "inverse-surface": "#263143",
        "background": "#f9f9ff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#311400",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "tertiary": "#924700",
        "outline-variant": "#c2c6d6",
        "on-secondary-fixed": "#0b1c30",
        "on-background": "#111c2d",
        "on-surface": "#111c2d",
        "on-secondary": "#ffffff",
        "outline": "#727785",
        "secondary": "#505f76",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb786",
        "inverse-primary": "#adc6ff",
        "inverse-on-surface": "#ecf1ff",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "on-error": "#ffffff",
        "surface-variant": "#d8e3fb",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "on-primary-fixed-variant": "#004395",
        "surface-container-highest": "#d8e3fb",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container": "#e7eeff",
        "primary": "#0058be",
        "on-tertiary-fixed-variant": "#723600",
        "on-surface-variant": "#424754",
        "surface-container-high": "#dee8ff",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-container": "#fefcff",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#2170e4",
        "on-primary": "#ffffff",
        "tertiary-container": "#b75b00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "max-width": "1280px",
        "sm": "8px",
        "gutter": "20px",
        "margin-desktop": "32px",
        "xs": "4px",
        "md": "16px",
        "margin-mobile": "16px",
        "xl": "40px",
        "base": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "headline-md": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "label-sm": ["Outfit"],
        "body-lg": ["Outfit"],
        "headline-lg": ["Outfit"],
        "label-md": ["Outfit"],
        "body-md": ["Outfit"],
        "display": ["Outfit"]
      }
    },
  },
  plugins: [],
}
